name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build (compile)
        run: npm run build

      - name: Unit tests
        run: npm test

      - name: Coverage
        run: npm run coverage

      - name: Upload gas report (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gas-report
          path: gas-report.md
          if-no-files-found: ignore
