name: Deploy OP Sepolia

on:
  workflow_dispatch: {}   # เปิดปุ่ม Run workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run build

      - name: Deploy to OP Sepolia
        env:
          OP_SEPOLIA_RPC_URL: ${{ secrets.OP_SEPOLIA_RPC_URL }}
          PRIVATE_KEY:        ${{ secrets.PRIVATE_KEY }}
          ETHERSCAN_API_KEY:  ${{ secrets.ETHERSCAN_API_KEY }}
          BASE_URI:           ${{ secrets.BASE_URI }}
        run: npm run deploy:op

      - name: Upload addresses.json
        uses: actions/upload-artifact@v4
        with:
          name: addresses
          path: web/addresses.json
          
      - name: Commit addresses.json back
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add web/addresses.json
          git commit -m "chore: update web/addresses.json [skip ci]" || echo "nothing to commit"
          git push    
