# .github/workflows/static.yml
name: Deploy static content to Pages

on:
  push:
    branches: [main]
    paths:
      - 'web/**'
      - '.github/workflows/static.yml'
  workflow_dispatch:

permissions:
  contents: write   # ต้องเป็น write เพื่อ commit/push addresses.json กลับ
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Build (compile + export ABI)
        run: npm run build

      - name: Configure Pages
        uses: actions/configure-pages@v5

      # อัปโหลดไฟล์ในโฟลเดอร์ web เป็น artifact สำหรับ Pages (อันเดียวเท่านั้น)
      - name: Upload site to Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # (ตัวเลือก) commit addresses.json กลับเข้า repo ถ้าถูกสร้าง/อัปเดต
      - name: Commit addresses.json back
        if: hashFiles('web/addresses.json') != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add web/addresses.json
          git commit -m "chore: update web/addresses.json [skip ci]" || echo "nothing to commit"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:${{ github.ref_name }}
